/* ${self.output_basename}.h
 *
 * Generated by pygi-codegen with the following command line:
 *     ${self.command_line}
*/

#ifndef __${self.output_basename.upper()}_H__
#define __${self.output_basename.upper()}_H__

#include <Python.h>
#include "${self.output_basename}-custom.h"

$python{
    from gi.codegen.codegen import current_context as self
    for class_builder in self.class_builders:
        magic_print("extern PyTypeObject ${class_builder.py_type_object_name};")
        class_builder.print_struct_def()
}end

PyObject * ${self.namespace_lower}_create_module (void);

#endif /*__${self.output_basename.upper()}_H__*/
